package com.playsphere.event;
import com.playsphere.common.ApiResponse;import com.playsphere.user.CurrentUserService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.Instant;import java.util.List;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class EventController{
 private final EventService service;private final CurrentUserService current;public EventController(EventService s,CurrentUserService c){service=s;current=c;}
 public record CreateEventRequest(@NotBlank @Size(max=160) String title,@Size(max=1200) String description,@NotBlank String sport,@NotBlank String eventType,@Pattern(regexp="INDIVIDUAL|TEAM") String registrationType,@NotBlank String city,@NotBlank String locality,String venueName,String turfId,@NotNull Instant startAt,@NotNull Instant endAt,@NotNull Instant registrationDeadline,@Min(1) int minPlayers,@Min(5) int maxPlayers,@NotNull @DecimalMin("0.00") BigDecimal entryFee,String bannerUrl,@Size(max=1500) String rules){}
 public record RegisterRequest(String teamId){}public record CancelEventRequest(@NotBlank @Size(max=500) String reason){}public record CreateMatchRequest(@NotBlank String title,@NotBlank String homeName,@NotBlank String awayName,@NotNull Instant scheduledAt,String venue){}public record ScoreRequest(@Min(0) int homeScore,@Min(0) int awayScore){}
 @GetMapping("/events") public ApiResponse<List<SportsEvent>> discover(){return ApiResponse.ok("Events",service.discover());}
 @GetMapping("/events/mine") @PreAuthorize("hasRole('ORGANIZER')") public ApiResponse<List<SportsEvent>> mine(Authentication a){return ApiResponse.ok("My events",service.mine(current.require(a).getId()));}
 @PostMapping("/events") @PreAuthorize("hasRole('ORGANIZER')") public ApiResponse<SportsEvent> create(@Valid @RequestBody CreateEventRequest r,Authentication a){return ApiResponse.ok("Event published",service.create(current.require(a).getId(),r));}
 @PatchMapping("/events/{id}/cancel") @PreAuthorize("hasRole('ORGANIZER')") public ApiResponse<SportsEvent> cancel(@PathVariable String id,@Valid @RequestBody CancelEventRequest r,Authentication a){return ApiResponse.ok("Event cancelled",service.cancel(current.require(a).getId(),id,r.reason()));}
 @PostMapping("/events/{id}/registrations") @PreAuthorize("hasRole('PLAYER')") public ApiResponse<EventRegistration> register(@PathVariable String id,@RequestBody(required=false) RegisterRequest r,Authentication a){return ApiResponse.ok("Registration created",service.register(current.require(a).getId(),id,r==null?null:r.teamId()));}
 @DeleteMapping("/events/{id}/registrations/mine") @PreAuthorize("hasRole('PLAYER')") public ApiResponse<Void> leave(@PathVariable String id,Authentication a){service.leave(current.require(a).getId(),id);return ApiResponse.ok("You left the event");}
 @GetMapping("/event-registrations/mine") @PreAuthorize("hasRole('PLAYER')") public ApiResponse<List<EventRegistration>> myRegistrations(Authentication a){return ApiResponse.ok("My registrations",service.myRegistrations(current.require(a).getId()));}
 @GetMapping("/events/{id}/registrations") @PreAuthorize("hasRole('ORGANIZER')") public ApiResponse<List<EventRegistration>> registrations(@PathVariable String id,Authentication a){return ApiResponse.ok("Registrations",service.eventRegistrations(current.require(a).getId(),id));}
 @GetMapping("/events/{id}/matches") public ApiResponse<List<Match>> matches(@PathVariable String id){return ApiResponse.ok("Matches",service.matches(id));}
 @PostMapping("/events/{id}/matches") @PreAuthorize("hasRole('ORGANIZER')") public ApiResponse<Match> createMatch(@PathVariable String id,@Valid @RequestBody CreateMatchRequest r,Authentication a){return ApiResponse.ok("Match scheduled",service.createMatch(current.require(a).getId(),id,r));}
 @PatchMapping("/matches/{id}/score") @PreAuthorize("hasRole('ORGANIZER')") public ApiResponse<Match> score(@PathVariable String id,@Valid @RequestBody ScoreRequest r,Authentication a){return ApiResponse.ok("Result published",service.score(current.require(a).getId(),id,r.homeScore(),r.awayScore()));}
}
