spring.application.name=api-gateway
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.routes[0].id=student-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://STUDENT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/students/**


# PlaySphere API Service Route

spring.cloud.gateway.server.webflux.routes[1].id=playsphere-api

spring.cloud.gateway.server.webflux.routes[1].uri=lb://PLAYSPHERE-API

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/**


# expose actuator endpoints
management.endpoints.web.exposure.include=*

# enable gateway actuator endpoints
management.endpoint.gateway.enabled=true
