package com.playsphere.turf;
import com.playsphere.common.ApiResponse;import com.playsphere.user.CurrentUserService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.Instant;import java.util.List;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class TurfController{
 private final TurfService service;private final CurrentUserService current;public TurfController(TurfService s,CurrentUserService c){service=s;current=c;}
 public record CreateTurfRequest(@NotBlank @Size(max=140) String name,@Size(max=1000) String description,@NotBlank String addressLine,@NotBlank String city,@NotBlank String locality,BigDecimal latitude,BigDecimal longitude,@NotBlank String sports,String amenities,@NotNull @DecimalMin("0.00") BigDecimal basePrice,String coverImageUrl){}
 public record CreateSlotRequest(@NotNull Instant startAt,@NotNull Instant endAt,@NotNull @DecimalMin("0.00") BigDecimal price){}public record CancelRequest(@NotBlank @Size(max=400) String reason){}public record CheckInRequest(@NotBlank String bookingCode,@NotBlank String qrToken){}public record CreateEquipmentRequest(@NotBlank @Size(max=120) String name,@Size(max=500) String description,@Min(0) int quantity,@NotNull @DecimalMin("0.00") BigDecimal pricePerBooking){}public record UpdateEquipmentRequest(@Min(0) int quantity,@NotNull @DecimalMin("0.00") BigDecimal pricePerBooking,boolean active){}public record SlotStatusRequest(@Pattern(regexp="AVAILABLE|BLOCKED") String status){}public record DecisionRequest(boolean approve,@Size(max=500) String reason){}
 @GetMapping("/turfs") public ApiResponse<List<Turf>> discover(){return ApiResponse.ok("Approved turfs",service.discover());}
 @GetMapping("/turfs/mine") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<List<Turf>> mine(Authentication a){return ApiResponse.ok("My turfs",service.mine(current.require(a).getId()));}
 @PostMapping("/turfs") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<Turf> create(@Valid @RequestBody CreateTurfRequest r,Authentication a){return ApiResponse.ok("Turf submitted for approval",service.create(current.require(a).getId(),r));}
 @GetMapping("/turfs/{id}/slots") public ApiResponse<List<TurfSlot>> slots(@PathVariable String id){return ApiResponse.ok("Available slots",service.availableSlots(id));}
 @PostMapping("/turfs/{id}/slots") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<TurfSlot> createSlot(@PathVariable String id,@Valid @RequestBody CreateSlotRequest r,Authentication a){return ApiResponse.ok("Slot created",service.createSlot(current.require(a).getId(),id,r));}
 @GetMapping("/turfs/{id}/slots/manage") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<List<TurfSlot>> manageSlots(@PathVariable String id,Authentication a){return ApiResponse.ok("Managed slots",service.ownerSlots(current.require(a).getId(),id));}
 @PatchMapping("/turfs/{turfId}/slots/{slotId}/status") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<TurfSlot> slotStatus(@PathVariable String turfId,@PathVariable String slotId,@Valid @RequestBody SlotStatusRequest r,Authentication a){return ApiResponse.ok("Slot status updated",service.slotStatus(current.require(a).getId(),turfId,slotId,r.status()));}
 @GetMapping("/turfs/{id}/equipment") public ApiResponse<List<TurfEquipment>> equipment(@PathVariable String id){return ApiResponse.ok("Turf equipment",service.equipment(id,false,null));}
 @GetMapping("/turfs/{id}/equipment/manage") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<List<TurfEquipment>> manageEquipment(@PathVariable String id,Authentication a){return ApiResponse.ok("Managed equipment",service.equipment(id,true,current.require(a).getId()));}
 @PostMapping("/turfs/{id}/equipment") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<TurfEquipment> addEquipment(@PathVariable String id,@Valid @RequestBody CreateEquipmentRequest r,Authentication a){return ApiResponse.ok("Equipment created",service.addEquipment(current.require(a).getId(),id,r));}
 @PatchMapping("/turfs/{turfId}/equipment/{equipmentId}") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<TurfEquipment> updateEquipment(@PathVariable String turfId,@PathVariable String equipmentId,@Valid @RequestBody UpdateEquipmentRequest r,Authentication a){return ApiResponse.ok("Equipment updated",service.updateEquipment(current.require(a).getId(),turfId,equipmentId,r));}
 @PostMapping("/bookings") @PreAuthorize("hasRole('PLAYER')") public ApiResponse<Booking> book(@RequestParam String slotId,Authentication a){return ApiResponse.ok("Booking created. Complete payment to confirm.",service.book(current.require(a).getId(),slotId));}
 @GetMapping("/bookings/mine") @PreAuthorize("hasRole('PLAYER')") public ApiResponse<List<Booking>> myBookings(Authentication a){return ApiResponse.ok("My bookings",service.playerBookings(current.require(a).getId()));}
 @GetMapping("/turfs/{id}/bookings") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<List<Booking>> ownerBookings(@PathVariable String id,Authentication a){return ApiResponse.ok("Turf bookings",service.ownerBookings(current.require(a).getId(),id));}
 @PostMapping("/bookings/{id}/qr") @PreAuthorize("hasRole('PLAYER')") public ApiResponse<Booking> qr(@PathVariable String id,Authentication a){return ApiResponse.ok("QR token generated",service.qr(current.require(a).getId(),id));}
 @PatchMapping("/bookings/{id}/cancel") @PreAuthorize("hasRole('PLAYER')") public ApiResponse<Void> cancel(@PathVariable String id,@Valid @RequestBody CancelRequest r,Authentication a){service.cancel(current.require(a).getId(),id,r.reason());return ApiResponse.ok("Booking cancelled");}
 @PostMapping("/bookings/check-in") @PreAuthorize("hasRole('TURF_OWNER')") public ApiResponse<Booking> checkIn(@Valid @RequestBody CheckInRequest r,Authentication a){return ApiResponse.ok("Check-in complete",service.checkIn(current.require(a).getId(),r.bookingCode(),r.qrToken()));}
 @GetMapping("/admin/turfs/pending") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public ApiResponse<List<Turf>> pending(){return ApiResponse.ok("Pending turfs",service.pending());}
 @PatchMapping("/admin/turfs/{id}") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public ApiResponse<Turf> decide(@PathVariable String id,@RequestBody DecisionRequest r,Authentication a){return ApiResponse.ok("Turf decision saved",service.decide(current.require(a).getId(),id,r.approve(),r.reason()));}
}
