package com.playsphere.turf;
import com.playsphere.common.Ids;import jakarta.persistence.*;import java.math.BigDecimal;import java.time.Instant;
@Entity @Table(name="turfs") public class Turf{
 @Id @Column(length=36) private String id;@Column(name="owner_user_id",nullable=false,length=36) private String ownerUserId;@Column(nullable=false,length=140) private String name;@Column(length=1000) private String description;@Column(name="address_line",nullable=false,length=220) private String addressLine;@Column(nullable=false,length=80) private String city;@Column(nullable=false,length=80) private String locality;@Column(precision=10,scale=7) private BigDecimal latitude;@Column(precision=10,scale=7) private BigDecimal longitude;@Column(nullable=false,length=300) private String sports;@Column(length=700) private String amenities;@Column(name="base_price",nullable=false,precision=12,scale=2) private BigDecimal basePrice;@Column(name="cover_image_url",length=700) private String coverImageUrl;@Column(nullable=false,length=24) private String status;@Column(name="rejection_reason",length=500) private String rejectionReason;@Column(name="created_at",nullable=false) private Instant createdAt;@Column(name="updated_at",nullable=false) private Instant updatedAt;
 protected Turf(){}public Turf(String owner,TurfController.CreateTurfRequest r,String validatedCoverImageUrl){id=Ids.uuid();ownerUserId=owner;name=r.name().trim();description=trim(r.description());addressLine=r.addressLine().trim();city=r.city().trim();locality=r.locality().trim();latitude=r.latitude();longitude=r.longitude();sports=r.sports().trim();amenities=trim(r.amenities());basePrice=r.basePrice();coverImageUrl=validatedCoverImageUrl;status="PENDING_APPROVAL";createdAt=updatedAt=Instant.now();}
 public String getId(){return id;}public String getOwnerUserId(){return ownerUserId;}public String getName(){return name;}public String getDescription(){return description;}public String getAddressLine(){return addressLine;}public String getCity(){return city;}public String getLocality(){return locality;}public BigDecimal getLatitude(){return latitude;}public BigDecimal getLongitude(){return longitude;}public String getSports(){return sports;}public String getAmenities(){return amenities;}public BigDecimal getBasePrice(){return basePrice;}public String getCoverImageUrl(){return coverImageUrl;}public String getStatus(){return status;}public String getRejectionReason(){return rejectionReason;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}
 public void decide(boolean approve,String reason){status=approve?"APPROVED":"REJECTED";rejectionReason=approve?null:trim(reason);updatedAt=Instant.now();}
 private static String trim(String value){return value==null||value.isBlank()?null:value.trim();}
}
