package com.playsphere.team;
import com.playsphere.common.Ids;
import jakarta.persistence.*;
import java.time.Instant;
@Entity @Table(name="recruitment_posts")
public class RecruitmentPost{
 @Id @Column(length=36) private String id;@Column(name="team_id",nullable=false,length=36) private String teamId;@Column(name="created_by_user_id",nullable=false,length=36) private String createdByUserId;@Column(nullable=false,length=140) private String title;@Column(nullable=false,length=80) private String sport;@Column(name="positions_needed",nullable=false,length=300) private String positionsNeeded;@Column(name="players_needed",nullable=false) private int playersNeeded;@Column(name="skill_level",nullable=false,length=32) private String skillLevel;@Column(nullable=false,length=80) private String city;@Column(nullable=false,length=80) private String locality;@Column(length=700) private String description;@Column(name="application_deadline") private Instant applicationDeadline;@Column(nullable=false,length=20) private String status;@Column(name="created_at",nullable=false) private Instant createdAt;@Column(name="updated_at",nullable=false) private Instant updatedAt;
 protected RecruitmentPost(){}public RecruitmentPost(String team,String creator,String title,String sport,String positions,int count,String skill,String city,String locality,String desc,Instant deadline){id=Ids.uuid();teamId=team;createdByUserId=creator;this.title=title;this.sport=sport;positionsNeeded=positions;playersNeeded=count;skillLevel=skill;this.city=city;this.locality=locality;description=desc;applicationDeadline=deadline;status="OPEN";createdAt=updatedAt=Instant.now();}
 public String getId(){return id;}public String getTeamId(){return teamId;}public String getCreatedByUserId(){return createdByUserId;}public String getTitle(){return title;}public String getSport(){return sport;}public String getPositionsNeeded(){return positionsNeeded;}public int getPlayersNeeded(){return playersNeeded;}public String getSkillLevel(){return skillLevel;}public String getCity(){return city;}public String getLocality(){return locality;}public String getDescription(){return description;}public Instant getApplicationDeadline(){return applicationDeadline;}public String getStatus(){return status;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}
 public void filledOne(){if(playersNeeded>0)playersNeeded--;if(playersNeeded==0)status="FILLED";updatedAt=Instant.now();}public void close(){status="CLOSED";updatedAt=Instant.now();}
}
